/**
 * Riječi za cjelovito podudaranje (normalizovano: mala slova, bez dijakritika).
 * Proširite listu po potrebi; ne koristimo regex nad cijelim tekstom da izbjegnemo lažne pozitive.
 */
export const PROFANITY_BLOCKLIST = new Set<string>([
  // English (common)
  'fuck',
  'fucking',
  'fucked',
  'shit',
  'bitch',
  'bastard',
  'asshole',
  'cunt',
  'dick',
  'cock',
  'piss',
  'slut',
  'whore',
  'nigger',
  'nigga',
  'fag',
  'faggot',
  'retard',
  'retarded',
  // Latin (balkanski / opšte)
  'kurac',
  'kurca',
  'kurčina',
  'picka',
  'pička',
  'pizda',
  'jebac',
  'jebač',
  'jebati',
  'jebem',
  'jebes',
  'jebiš',
  'sisa',
  'sisate',
  'govno',
  'govna',
  'serem',
  'seres',
  'seriš',
  'smrd',
  'budala',
  'kreten',
  'idiot',
  'debil',
  'glupan',
  'kurvin',
  'drolja',
  // Ćirilica (iste koncepte)
  'курац',
  'пичка',
  'пизда',
  'јебати',
  'јебем',
  'говно',
  'сиса',
  'кретен',
  'идиот',
  'дебил',
])
